#%RAML 1.0 Trait
description: JWT token
usage: Apply to resources require JWT token for authorization and/or authentication.

headers:
    Authorization:
        description: Bearer JWT token
        type: string