#%RAML 1.0 Trait
description: error response returned by API
usage: apply to all

responses:
  400:
    description: Bad Request
    body:
      application/json:
        type: !include /exchange_modules/693029ff-19d1-4263-b6bb-08de4d767d9a/error/2.0.1/error.raml
  401:
    description: Unauthorized
    body:
      application/json:
        type: !include /exchange_modules/693029ff-19d1-4263-b6bb-08de4d767d9a/error/2.0.1/error.raml
  403:
    description: Forbidden
    body:
      application/json:
        type: !include /exchange_modules/693029ff-19d1-4263-b6bb-08de4d767d9a/error/2.0.1/error.raml
  404:
    description: Resource not found
    body:
      application/json:
        type: !include /exchange_modules/693029ff-19d1-4263-b6bb-08de4d767d9a/error/2.0.1/error.raml
  500:
    description: Internl Server Error
    body:
      application/json:
        type: !include /exchange_modules/693029ff-19d1-4263-b6bb-08de4d767d9a/error/2.0.1/error.raml