#%RAML 1.0 DataType
type: object
displayName: Customer Type
properties:
  name:
    required: false
    type: string
    example: "Arijit Ghosh"
  age:
    required: false
    type: integer
    example: 35
  email:
    required: false
    type: string
    example: "xyz@myflight.com"





  